version: 2
jobs:
  build:
    
    working_directory: ~/yo-cordapp

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

     
      - run: ./gradlew deployNodes

      - setup_remote_docker   # (2)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      #- run:
      #    name: Install Docker client
      #    command: |
      #      set -x
      #      VER="17.05.0-ce"
      #      #curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.05.0-ce.tgz
      #      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #      mv /tmp/docker/* /usr/bin

            
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   labsji/yo-cordapp:$TAG build/nodes/Controller     
          docker login -u $DOCKER_USER -p $DOCKER_PASS        
          docker push labsji/yo-cordapp:$TAG


     # - store_artifacts:
     #     path: build/nodes
      

      
