version: 2
jobs:
  build:
    
    working_directory: ~/yo-cordapp

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

     
      - run: ./gradlew deployNodes

      
